openapi: 3.0.0
info:
  title: Todo APP
  version: 1.0.0
  description: This is a Todo App for Web development excercise
servers:
  - url: https://eb12f861-97fb-4590-b42f-d8a6cb9178d9.mock.pstmn.io
paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    taskName:
                      type: string
                    status:
                      type: string
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskName:
                  type: string
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: number
                  taskName:
                    type: string
                  status:
                    type: string

    put:
      summary: Markdone a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id: 
                  type: number
                taskName:
                  type: string
                status: 
                  type: string
                
      responses:
        '200':
          description: Task markdone successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: number
                  taskName:
                    type: string
                  status: 
                    type: string

  /tasks/mark-not-done-task:
    put:
      summary: Mark a task not done
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id: 
                  type: number
                taskName:
                  type: string
                status: 
                  type: string
                
      responses:
        '200':
          description: Mark task not done successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: number
                  taskName:
                    type: string
                  status: 
                    type: string

  /tasks/delete-task:
    put:
      summary: Delete a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id: 
                  type: number
                taskName:
                  type: string
                status: 
                  type: string
                
      responses:
        '200':
          description: Delete a task successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: number
                  taskName:
                    type: string